# Generated by Django 3.1.1 on 2020-09-26 01:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0010_auto_20200926_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='ACFT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushups', models.CharField(blank=True, max_length=2)),
                ('ball', models.CharField(blank=True, max_length=2)),
                ('sprint_drag', models.CharField(blank=True, max_length=5)),
                ('leg_tucks', models.CharField(blank=True, max_length=2)),
                ('run', models.CharField(blank=True, max_length=5)),
                ('dead_lift', models.CharField(blank=True, max_length=3)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
