# Generated by Django 3.1.1 on 2020-09-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_acft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acft',
            name='ball',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
