# Generated by Django 3.1.1 on 2020-10-15 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20201015_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acft',
            name='dead_lift',
            field=models.IntegerField(choices=[(140, 140), (150, 150), (160, 160), (170, 170), (180, 180), (190, 190), (200, 200), (210, 210), (220, 220), (230, 230), (240, 240), (250, 250), (260, 260), (270, 270), (280, 280), (290, 290), (300, 300), (310, 310), (320, 320), (330, 330), (340, 340)], max_length=3),
        ),
        migrations.AlterField(
            model_name='acft',
            name='leg_tucks',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20)], max_length=2),
        ),
    ]
